.\" This page Copyright (C) 2013 Jonathan Klee <klee.jonathan@gmail.com>
.TH NGP 1 "31 December 2013"
.SH NAME
ngp \- Ncurses code parsing tools
.SH SYNOPSIS
.ft B
.B ngp
.RB [OPTION]...
.RI pattern
.RI [directory]
.br
.B ngp -l
.br
.B ngp -p index
.SH DESCRIPTION
ngp lets you look for a pattern in your source code directory and display results in ncurses.
ngp lets you browse results in a Vim-like style.
ngp lets you open a result with your favorite editor at the right line.

.TP
use 'k' and 'j' to browser results up and down.
.TP
use 'K' and 'J' to switch page up and the down.
.TP
use 'p' or Enter to open the occurency with your editor.
.TP
use 'q' to quit.
.TP
When ngplog is true in ngprc, ngp -l lets you list the latest files opened with ngp.
.TP
ngp -p index lets you open the file corresponding to the specified index.

.SS Options
.TP
\fB-i\fP
case insensitive
.TP
\fB-r\fP
raw mode. Parse each file of the directory
.TP
\fB-t extension\fP
look into files that have this extension
.TP
\fB-I name\fP
ignore file that have this name
.TP
\fB-e\fP
regexp mode. Pattern is a regular expression
.TP
\fB-l\fP
list latest files opened with ngp
.TP
\fB-v\fP
output version information and exit
.SH AUTHOR
Written by Jonathan Klee <klee.jonathan@gmail.com>
